/*
 * -------------------------------------------------------
 * Migration: Phase 5 — QMS Business Function Tables
 * Étapes 18–22 — Phase 5: Fonctions Métier QMS
 * Ref: section 3.4 du cahier des charges
 *
 * Tables:
 *   - pfmea_reports       (Étape 18)
 *   - audit_checklists    (Étape 20)
 *   - audit_plans         (Étape 20)
 *   - continuous_improvement_insights (Étape 22)
 * -------------------------------------------------------
 */

-- =============================================
-- Table: pfmea_reports
-- =============================================
create table if not exists public.pfmea_reports (
    id                uuid primary key default extensions.uuid_generate_v4(),
    user_id           uuid not null references auth.users(id) on delete cascade,
    process           text not null,
    product           text not null,
    defects           jsonb not null default '[]'::jsonb,
    generated_content text not null default '',
    template_ids      jsonb not null default '[]'::jsonb,
    created_at        timestamptz default now()
);

comment on table public.pfmea_reports is 'PFMEA/AMDEC reports generated by the AI assistant (F3)';

-- =============================================
-- Table: audit_checklists
-- =============================================
create table if not exists public.audit_checklists (
    id                  uuid primary key default extensions.uuid_generate_v4(),
    user_id             uuid not null references auth.users(id) on delete cascade,
    standard            text not null check (standard in ('ISO9001', 'IATF16949')),
    process_scope       text not null,
    content             jsonb not null default '[]'::jsonb,
    source_document_ids jsonb not null default '[]'::jsonb,
    created_at          timestamptz default now()
);

comment on table public.audit_checklists is 'Audit checklists generated for ISO 9001 / IATF 16949 (F4)';

-- =============================================
-- Table: audit_plans
-- =============================================
create table if not exists public.audit_plans (
    id                 uuid primary key default extensions.uuid_generate_v4(),
    checklist_id       uuid not null references public.audit_checklists(id) on delete cascade,
    sampling_strategy  text not null default 'standard',
    questions          jsonb not null default '[]'::jsonb,
    created_at         timestamptz default now()
);

comment on table public.audit_plans is 'Audit plans with questions and sampling strategies (F4)';

-- =============================================
-- Table: continuous_improvement_insights
-- =============================================
create table if not exists public.continuous_improvement_insights (
    id                 uuid primary key default extensions.uuid_generate_v4(),
    recurring_finding  text not null,
    linked_documents   jsonb not null default '[]'::jsonb,
    recommendation     text not null,
    created_at         timestamptz default now()
);

comment on table public.continuous_improvement_insights is 'AI-generated insights for continuous QMS improvement (Extension)';

-- =============================================
-- Enable RLS
-- =============================================
alter table public.pfmea_reports enable row level security;
alter table public.audit_checklists enable row level security;
alter table public.audit_plans enable row level security;
alter table public.continuous_improvement_insights enable row level security;

-- =============================================
-- RLS Policies: pfmea_reports
-- Users see/create their own; admin sees all
-- =============================================
create policy pfmea_reports_select on public.pfmea_reports
    for select to authenticated
    using (
        auth.uid() = user_id
        or exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

create policy pfmea_reports_insert on public.pfmea_reports
    for insert to authenticated
    with check (auth.uid() = user_id);

create policy pfmea_reports_delete on public.pfmea_reports
    for delete to authenticated
    using (
        auth.uid() = user_id
        or exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

-- =============================================
-- RLS Policies: audit_checklists
-- Users see/create their own; admin sees all
-- =============================================
create policy audit_checklists_select on public.audit_checklists
    for select to authenticated
    using (
        auth.uid() = user_id
        or exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

create policy audit_checklists_insert on public.audit_checklists
    for insert to authenticated
    with check (auth.uid() = user_id);

create policy audit_checklists_delete on public.audit_checklists
    for delete to authenticated
    using (
        auth.uid() = user_id
        or exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

-- =============================================
-- RLS Policies: audit_plans
-- Via owning checklist's user_id; admin sees all
-- =============================================
create policy audit_plans_select on public.audit_plans
    for select to authenticated
    using (
        exists (
            select 1 from public.audit_checklists c
            where c.id = audit_plans.checklist_id
            and (c.user_id = auth.uid() or exists (
                select 1 from public.accounts a
                where a.id = auth.uid() and a.role = 'admin'
            ))
        )
    );

create policy audit_plans_insert on public.audit_plans
    for insert to authenticated
    with check (
        exists (
            select 1 from public.audit_checklists c
            where c.id = audit_plans.checklist_id
            and c.user_id = auth.uid()
        )
    );

create policy audit_plans_delete on public.audit_plans
    for delete to authenticated
    using (
        exists (
            select 1 from public.audit_checklists c
            where c.id = audit_plans.checklist_id
            and (c.user_id = auth.uid() or exists (
                select 1 from public.accounts a
                where a.id = auth.uid() and a.role = 'admin'
            ))
        )
    );

-- =============================================
-- RLS Policies: continuous_improvement_insights
-- Admin-only access
-- =============================================
create policy ci_insights_select on public.continuous_improvement_insights
    for select to authenticated
    using (
        exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

create policy ci_insights_insert on public.continuous_improvement_insights
    for insert to authenticated
    with check (
        exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

create policy ci_insights_update on public.continuous_improvement_insights
    for update to authenticated
    using (
        exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

create policy ci_insights_delete on public.continuous_improvement_insights
    for delete to authenticated
    using (
        exists (
            select 1 from public.accounts a
            where a.id = auth.uid() and a.role = 'admin'
        )
    );

-- =============================================
-- Indexes
-- =============================================
create index if not exists idx_pfmea_reports_user_id
    on public.pfmea_reports (user_id);

create index if not exists idx_pfmea_reports_created_at
    on public.pfmea_reports (created_at desc);

create index if not exists idx_audit_checklists_user_id
    on public.audit_checklists (user_id);

create index if not exists idx_audit_checklists_standard
    on public.audit_checklists (standard);

create index if not exists idx_audit_checklists_created_at
    on public.audit_checklists (created_at desc);

create index if not exists idx_audit_plans_checklist_id
    on public.audit_plans (checklist_id);

create index if not exists idx_ci_insights_created_at
    on public.continuous_improvement_insights (created_at desc);

-- =============================================
-- Grants
-- =============================================
grant select, insert, delete on public.pfmea_reports to authenticated, service_role;
grant select, insert, delete on public.audit_checklists to authenticated, service_role;
grant select, insert, delete on public.audit_plans to authenticated, service_role;
grant select, insert, update, delete on public.continuous_improvement_insights to authenticated, service_role;
